services:
  db:
    image: pgvector/pgvector:0.8.1-pg17-bookworm
    container_name: backend-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data: